APLICATIONNAME : "GO_MERCHANT"
JWTKEY : "P@ssw0rd"
JWTDURATION: "60"

SERVERURL: "localhost"
SERVERPORT: "8080"

DBHOST: "localhost"
DBUSERNAME: "postgres"
DBPASSWORD: "5434jago"
DBPORT: "5432"
DBNAME: "go_merchant"

REDISURL: "127.0.0.1"
REDISPORT: "6379"
REDISPASSWORD: ""